language: node_js
node_js:
- '6'
services:
  - rabbitmq
after_script: PINGINTERVAL=1000 istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
